version: '3.7'

services:
  sheetbase:
    build: .
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/var/www
